on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create a release

jobs:
  build:
    name: Create Release
    if: github.repository == 'cilium/hubble'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # renovate: tag=3.5.2
      - name: Generate artifacts
        run: make release
      - name: Create Release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # renovate: tag=1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true # turn this to false once release notes are automatically added
          prerelease: false
          body: |
            Note for maintainers:: Please, update the desciption with the actual release notes (see RELEASE.md for instructions).
      - name: Upload artifacts
        id: upload-release-artifacts
        uses: skx/github-action-publish-binaries@44887b225ceca96efd8a912d39c09ad70312af31
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ steps.create_release.outputs.id }}
          args: 'release/*'
