name: Run static checks and unit tests
on:
  push:
    branches:
      - master
      - v*
  pull_request:
    branches:
    - master
    - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        path: go/src/github.com/cilium/hubble
    - uses: actions/setup-go@v1
      with:
        go-version: '1.14.11'
    - name: Run static checks
      env:
        GOPATH: /home/runner/work/hubble/go
      run: |
        export PATH=${PATH}:${GOPATH}/bin
        GO111MODULE=off go get -u github.com/gordonklaus/ineffassign
        GO111MODULE=off go get -u golang.org/x/lint/golint
        make check
    - name: Run unit tests
      run: make test
    - name: Generate artifacts
      run: make release
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: release
        path: release
